# To use js-dependency-update action
# Workflow is in charge of running the action or determining the schedule.
# Not the action itself

name: Custom Actions - JS
run-name: Custom Actions - JS | BB - ${{inputs.base-branch}} TB - ${{inputs.head-branch}} - WD ${{inputs.working-directory}}

on:
  workflow_dispatch:
    inputs:
      base-branch:
        type: string
        default: main
      head-branch:
        type: string
        default: update-dependencies
      working-directory:
        type: string
        default: "."
      debug:
        type: boolean
        default: false

# Change the permissions granted to the GITHUB_TOKEN
# Repo setting → Actions → General → Workflow permissions
# Repo에서 옵션이 grayed out되어있으면 organization에서 바꿀 수 있다
permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
        with:
          base-branch: ${{inputs.base-branch}}
          head-branch: ${{inputs.head-branch}}
          working-directory: ${{inputs.working-directory}}
          gh-token: ${{secrets.GITHUB_TOKEN}}
          debug: ${{inputs.debug}}
