# To use js-dependency-update action
# Workflow is in charge of running the action or determining the schedule.
# Not the action itself

name: Custom Actions - JS
run-name: Custom Actions - JS | BB - ${{inputs.base-branch}} TB - ${{inputs.target-branch}} - WD ${{inputs.working-directory}}

on:
  workflow_dispatch:
    inputs:
      base-branch:
        type: string
        default: main
      target-branch:
        type: string
        default: update-dependencies
      working-directory:
        type: string
        default: /

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
        with:
          base-branch: ${{inputs.base-branch}}
          target-branch: ${{inputs.target-branch}}
          working-directory: ${{inputs.working-directory}}
