name: Custom Actions - Composite
run-name: Custom Actions - Composite | env -${{inputs.target-env}}

on:
  workflow_dispatch:
    # workflow_dispatch에 input을 달아줄 수 있다
    inputs:
      target-env:
        description: Which environment to target for dependency installation
        type: choice
        options:
          - dev
          - prod

env:
  working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node and NPM Dependencies
        id: setup-deps
        # Use our composite action (absolute path)
        # checkout action을 먼저 사용해줘야 한다
        uses: ./.github/actions/composite-cache-dependencies
        with:
          # custom action이 필요로하는 args
          node-version: 23.x
          working-dir: ${{env.working-directory}}
          target-env: ${{inputs.target-env}}
      - name: Print setup deps output
        run: |
          echo "Installed dependencies: ${{steps.setup-deps.outputs.installed-deps}}"

      - name: Test
        run: echo 'Mock test'
      - name: Build
        run: npm run build
